### PR TITLE
Updated to Cordova 2.9, and more...

### PR DESCRIPTION
**Pull request by gaetansenn**
- Updated to Cordova 2.9
- Check if phone number isn't null.
- Add support of call with platforms that support tel protocol.

### CODE REVIEW

**Comment by trevoriancox** [comment]
Looks good to me!

**Comment by j-mcnally** [comment]
Sounds good thank you ill merge this tonite. Any one using cocoa pods with cordova should we make a pod for this?

**Comment by micboe** [comment]
Hi Gaetan,

nice work! One short quesition, is it planned or possible that you submit your Plugin to PhoneGap Build? 

https://build.phonegap.com/docs/plugins-using 

That would be very usefull for all who use the PhoneGap Build service.

Thank you for the answer.

**Comment by j-mcnally** [comment]
Micboe is there extra config / xml to be added? If so can you add it and send a PR

**Comment by gaetansenn** [comment]
Thank you all :). @j-mcnally : you didn't forget to merge my pull request ?

**Pull request closed without merging**
